[package]
version = "0.1.0"
name = "sp1-helios-primitives"
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
eyre = { workspace = true }
ssz-rs = { workspace = true }
hex = { workspace = true }
serde_with = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
consensus-core = { workspace = true }
common = { workspace = true }
alloy-sol-types = { workspace = true }
alloy-primitives = { workspace = true }
