[package]
name = "example"
version = "0.1.0"
license.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
consensus-core = { workspace = true }
alloy-primitives = { workspace = true }
eyre = { workspace = true }
