[package]
version = "0.1.0"
name = "helios-script"
edition = "2021"


[[bin]]
name = "genesis"
path = "./bin/genesis.rs"


[[bin]]
name = "run"
path = "./bin/run.rs"

[[bin]]
name = "operator"
path = "./bin/operator.rs"

[dependencies]
dotenv = { workspace = true }
eyre = { workspace = true }
sp1-sdk = { workspace = true }
tokio = { workspace = true }
helios = { workspace = true }
sp1-helios-primitives = { path = "../primitives" }
tracing = { workspace = true }
serde = { workspace = true }
ssz-rs = { workspace = true }
thiserror = { workspace = true }
ethers = { workspace = true }
zduny-wasm-timer = { workspace = true }
serde_cbor = { workspace = true }
hex = { workspace = true }
alloy-sol-types = {workspace = true}
clap = { workspace = true }
log = { workspace = true }
env_logger = { workspace = true }
alloy-primitives = {workspace = true}

anyhow = { workspace = true }
reqwest = { workspace = true }

[build-dependencies]
sp1-helper = { workspace = true }
[patch.crates-io]
sha2-v0-9-9 = { git = "https://github.com/sp1-patches/RustCrypto-hashes", package = "sha2", branch = "patch-sha2-v0.9.9" }
sha2-v0-10-8 = { git = "https://github.com/sp1-patches/RustCrypto-hashes", package = "sha2", branch = "patch-sha2-v0.10.8" }
tiny-keccak = { git = "https://github.com/sp1-patches/tiny-keccak", branch = "patch-v2.0.2" }
milagro_bls = { package = "bls12_381", git = "https://github.com/succinctlabs/bls12_381"} 