[workspace]
[package]
version = "0.1.0"
name = "sp1-helios-script"
edition = "2021"


[[bin]]
name = "genesis"
path = "./bin/genesis.rs"

[[bin]]
name = "operator"
path = "./bin/operator.rs"

[[bin]]
name = "gen-inputs"
path = "./bin/gen-inputs.rs"

[dependencies]
dotenv = "0.15.0"
eyre = "0.6.12"
sp1-sdk = "1.2.0-rc1"
tokio = "1.38.0"
helios = { path = "../../helios" }
sp1-helios-primitives = { path = "../primitives" }
tracing = "0.1.37"
serde = "1.0.203"
ssz-rs = { package = "ssz_rs", version = "0.9.0" }
thiserror = "1.0.61"
zduny-wasm-timer = "0.2.8"
serde_cbor = "0.11.2"
hex = "0.4.3"
serde_json = "1.0.125"
alloy-sol-types = "0.7.7"
clap = "4.5.9"
log = "0.4.22"
env_logger = "0.11.3"
alloy-primitives = "0.7.7"
alloy = { version = "0.1.1", features = ["full"] }
anyhow = "1.0.86"
reqwest = "0.12.5"
tree_hash = "0.7.0"

[build-dependencies]
sp1-helper = "1.2.0-rc1"

[patch.crates-io]
sha2-v0-9-9 = { git = "https://github.com/sp1-patches/RustCrypto-hashes", package = "sha2", branch = "patch-sha2-v0.9.9" }
sha2-v0-10-8 = { git = "https://github.com/sp1-patches/RustCrypto-hashes", package = "sha2", branch = "patch-sha2-v0.10.8" }
tiny-keccak = { git = "https://github.com/sp1-patches/tiny-keccak", branch = "patch-v2.0.2" }
