[package]
version = "0.1.0"
name = "helios-program"
edition = "2021"

[dependencies]
sp1-zkvm = { workspace = true }
common = { workspace = true }
consensus-core = { workspace = true }
serde_cbor = { workspace = true }
sp1-helios-primitives = { workspace = true }
# alloy-sol-types = "0.7.7"
ssz-rs = { workspace = true }
# alloy-primitives = "0.7.7"
hex = { workspace = true }
