[package]
version = "0.1.0"
name = "helios-program"
edition = "2021"

[dependencies]
sp1-zkvm = { workspace = true }
common = { workspace = true, branch="patched"  }
consensus-core = { workspace = true, branch="patched" }
serde_cbor = { workspace = true }
sp1-helios-primitives = { workspace = true }
alloy-sol-types = {workspace = true}
ssz-rs = { workspace = true }
alloy-primitives = { workspace = true }
hex = { workspace = true }
